<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>常见的错误类型</title>
</head>
<script>
    /*
     * 进一步理解JS中的错误(error)和错误的处理
     * 1、错误的类型
     * 	Error:所有错误的父类型
     * 	ReferenceError:引用的变量不存在
     *  TypeError:数据类型不正确错误
     *  RangeError:数据值不在其所允许的范围内
     *  SyntaxError:语法错误
     * 2、 错误处理
     * 捕获错误： try ... catch
     * 抛出错误： throw ... error
     * 3、 错误对象
     * message 属性：错误相关信息
     * stack 属性： 函数调用栈记录信息 
     */
    // 1、 常见内置错误
    //  ReferenceError:引用的变量不存在
    // console.log(a);	// Uncaught ReferenceError: a is not defined
    // console.log('-------'); // 没有捕获错误 下面代码不会执行
    //  TypeError:数据类型不正确错误
    // let b = null;
    // b.xxx();
    // console.log(b.xxx);  // Uncaught TypeError: Cannot read property 'xxx' of null
    //  RangeError:数据值不在其所允许的范围内
    // function fn() {
    //     fn(); // Uncaught RangeError: Maximum call stack size exceeded
    // }
    // fn();
    //  SyntaxError:语法错误
    // let a = """";  //SyntaxError: Unexpected String;

    // 2、 错误处理
    // 捕获错误： try ... catch
    // try {
    //     let b = null;
    //     b.xxx();
    // } catch (error) {
    //     console.log(error.message);
    //     console.log(error.stack);
    // }
    // console.log('出错之后');
    // 抛出错误： throw ... error
    function something() {
        if (Date.now() % 2 === 1) {
            console.log('当前时间为奇数，可以执行任务');
        } else { //如果时间是偶数抛出异常，由调用者来处理。
            throw new Error('当前时间为偶数，无法执行任务');
        }
    }

    // 捕获处理异常
    try {
        something();
    } catch (error) {
        alert(error.message);
    }
</script>

<body>

</body>

</html>